/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Dimension;
import javax.swing.JDesktopPane;


public class MenuTienda extends javax.swing.JFrame {

    public static JDesktopPane jDesktopPane_menu;
    
    public MenuTienda() {
        initComponents();
        /*this.setSize(new Dimension(1200,700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de ventas CAMUCHITA");
        
        this.setLayout(null);
        jDesktopPane_menu = new  JDesktopPane();
        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_menu.setBounds(0,0,ancho,(alto-110));
        this.add(jDesktopPane_menu);*/
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        dskPaneSistema = new javax.swing.JPanel();
        jtxNombreEmpleado = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1_nuevo_cliente = new javax.swing.JMenuItem();
        jMenuItem2_gestionar_cliente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3_nuevo_producto = new javax.swing.JMenuItem();
        jMenuItem4_gestionar_producto = new javax.swing.JMenuItem();
        jMenuItem5_actualizar_stock = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6_nueva_categoria = new javax.swing.JMenuItem();
        jMenuItem7_gestionar_categoria = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9_nueva_venta = new javax.swing.JMenuItem();
        jMenuItem10_gestionar_venta = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem11_reportes_clientes = new javax.swing.JMenuItem();
        jMenuItem12_reportes_categorias = new javax.swing.JMenuItem();
        jMenuItem13_reporte_productos = new javax.swing.JMenuItem();
        jMenuItem14_reporte_ventas = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mncerrarPanel = new javax.swing.JMenuItem();
        volvermenu = new javax.swing.JMenuItem();

        jMenuItem8.setText("jMenuItem8");

        jMenu7.setText("File");
        jMenuBar2.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar2.add(jMenu8);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        dskPaneSistema.setBackground(new java.awt.Color(255, 255, 153));

        jtxNombreEmpleado.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jtxNombreEmpleado.setText("jLabel1");

        javax.swing.GroupLayout dskPaneSistemaLayout = new javax.swing.GroupLayout(dskPaneSistema);
        dskPaneSistema.setLayout(dskPaneSistemaLayout);
        dskPaneSistemaLayout.setHorizontalGroup(
            dskPaneSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dskPaneSistemaLayout.createSequentialGroup()
                .addGap(0, 786, Short.MAX_VALUE)
                .addComponent(jtxNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        dskPaneSistemaLayout.setVerticalGroup(
            dskPaneSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dskPaneSistemaLayout.createSequentialGroup()
                .addGap(0, 602, Short.MAX_VALUE)
                .addComponent(jtxNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jMenu1.setText("Clientes");
        jMenu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(200, 50));

        jMenuItem1_nuevo_cliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem1_nuevo_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-cliente.png"))); // NOI18N
        jMenuItem1_nuevo_cliente.setText("Nuevo Cliente");
        jMenuItem1_nuevo_cliente.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem1_nuevo_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_nuevo_clienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1_nuevo_cliente);

        jMenuItem2_gestionar_cliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem2_gestionar_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jMenuItem2_gestionar_cliente.setText("Gestionar Cliente");
        jMenuItem2_gestionar_cliente.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem2_gestionar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2_gestionar_clienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2_gestionar_cliente);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        jMenu2.setText("Productos");
        jMenu2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(200, 50));

        jMenuItem3_nuevo_producto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem3_nuevo_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-producto.png"))); // NOI18N
        jMenuItem3_nuevo_producto.setText("Nuevo Producto");
        jMenuItem3_nuevo_producto.setPreferredSize(new java.awt.Dimension(200, 33));
        jMenuItem3_nuevo_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3_nuevo_productoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3_nuevo_producto);

        jMenuItem4_gestionar_producto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem4_gestionar_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        jMenuItem4_gestionar_producto.setText("Gestionar Productos");
        jMenuItem4_gestionar_producto.setPreferredSize(new java.awt.Dimension(200, 33));
        jMenuItem4_gestionar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4_gestionar_productoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4_gestionar_producto);

        jMenuItem5_actualizar_stock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem5_actualizar_stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        jMenuItem5_actualizar_stock.setText("Actualizar Stock");
        jMenuItem5_actualizar_stock.setPreferredSize(new java.awt.Dimension(200, 33));
        jMenuItem5_actualizar_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5_actualizar_stockActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5_actualizar_stock);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        jMenu3.setText("Categorias");
        jMenu3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(200, 50));

        jMenuItem6_nueva_categoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem6_nueva_categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        jMenuItem6_nueva_categoria.setText("Nueva Categoria");
        jMenuItem6_nueva_categoria.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem6_nueva_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6_nueva_categoriaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6_nueva_categoria);

        jMenuItem7_gestionar_categoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem7_gestionar_categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        jMenuItem7_gestionar_categoria.setText("Gestionar Categoria");
        jMenuItem7_gestionar_categoria.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem7_gestionar_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7_gestionar_categoriaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7_gestionar_categoria);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrito.png"))); // NOI18N
        jMenu4.setText("Facturar");
        jMenu4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(200, 50));

        jMenuItem9_nueva_venta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem9_nueva_venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir.png"))); // NOI18N
        jMenuItem9_nueva_venta.setText("Nueva Venta");
        jMenuItem9_nueva_venta.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu4.add(jMenuItem9_nueva_venta);

        jMenuItem10_gestionar_venta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem10_gestionar_venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        jMenuItem10_gestionar_venta.setText("Gestionar Ventas");
        jMenuItem10_gestionar_venta.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu4.add(jMenuItem10_gestionar_venta);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reportes.png"))); // NOI18N
        jMenu5.setText("Reportes");
        jMenu5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu5.setPreferredSize(new java.awt.Dimension(200, 50));

        jMenuItem11_reportes_clientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem11_reportes_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        jMenuItem11_reportes_clientes.setText("Reportes Clientes");
        jMenuItem11_reportes_clientes.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu5.add(jMenuItem11_reportes_clientes);

        jMenuItem12_reportes_categorias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem12_reportes_categorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        jMenuItem12_reportes_categorias.setText("Reportes Categorias");
        jMenuItem12_reportes_categorias.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu5.add(jMenuItem12_reportes_categorias);

        jMenuItem13_reporte_productos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem13_reporte_productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        jMenuItem13_reporte_productos.setText("Reporte Productos");
        jMenuItem13_reporte_productos.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem13_reporte_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13_reporte_productosActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem13_reporte_productos);

        jMenuItem14_reporte_ventas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem14_reporte_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        jMenuItem14_reporte_ventas.setText("Reporte Ventas");
        jMenuItem14_reporte_ventas.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenuItem14_reporte_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14_reporte_ventasActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem14_reporte_ventas);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historial1.png"))); // NOI18N
        jMenu6.setText("Volver");
        jMenu6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(200, 50));

        mncerrarPanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mncerrarPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/CERRAR.png"))); // NOI18N
        mncerrarPanel.setText("Cerrar");
        mncerrarPanel.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu6.add(mncerrarPanel);

        volvermenu.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        volvermenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/VOL3.png"))); // NOI18N
        volvermenu.setText("Volver");
        jMenu6.add(volvermenu);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPaneSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPaneSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1_nuevo_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_nuevo_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1_nuevo_clienteActionPerformed

    private void jMenuItem4_gestionar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4_gestionar_productoActionPerformed
        /*InterGestionarProducto interGestionarProducto= new InterGestionarProducto();
        jDesktopPane_menu.add(interGestionarProducto);
        interGestionarProducto.setVisible(true);*/
    }//GEN-LAST:event_jMenuItem4_gestionar_productoActionPerformed

    private void jMenuItem2_gestionar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2_gestionar_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2_gestionar_clienteActionPerformed

    private void jMenuItem13_reporte_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13_reporte_productosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13_reporte_productosActionPerformed

    private void jMenuItem14_reporte_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14_reporte_ventasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem14_reporte_ventasActionPerformed

    private void jMenuItem5_actualizar_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5_actualizar_stockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5_actualizar_stockActionPerformed

    private void jMenuItem6_nueva_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6_nueva_categoriaActionPerformed
        /*InterCategoria interCategoria= new InterCategoria();
        jDesktopPane_menu.add(interCategoria);
        interCategoria.setVisible(true);*/
    }//GEN-LAST:event_jMenuItem6_nueva_categoriaActionPerformed

    private void jMenuItem7_gestionar_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7_gestionar_categoriaActionPerformed
        
        /*InterGestionarCategoria interGestionarCategoria= new InterGestionarCategoria();
        jDesktopPane_menu.add(interGestionarCategoria);
        interGestionarCategoria.setVisible(true);*/
            
        
    }//GEN-LAST:event_jMenuItem7_gestionar_categoriaActionPerformed

    private void jMenuItem3_nuevo_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3_nuevo_productoActionPerformed
         
        /*InterProducto interProducto= new InterProducto();
        jDesktopPane_menu.add(interProducto);
        interProducto.setVisible(true);*/
        
    }//GEN-LAST:event_jMenuItem3_nuevo_productoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuTienda().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel dskPaneSistema;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    public javax.swing.JMenu jMenu3;
    public javax.swing.JMenu jMenu4;
    public javax.swing.JMenu jMenu5;
    public javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    public javax.swing.JMenuItem jMenuItem10_gestionar_venta;
    public javax.swing.JMenuItem jMenuItem11_reportes_clientes;
    public javax.swing.JMenuItem jMenuItem12_reportes_categorias;
    public javax.swing.JMenuItem jMenuItem13_reporte_productos;
    public javax.swing.JMenuItem jMenuItem14_reporte_ventas;
    public javax.swing.JMenuItem jMenuItem1_nuevo_cliente;
    public javax.swing.JMenuItem jMenuItem2_gestionar_cliente;
    public javax.swing.JMenuItem jMenuItem3_nuevo_producto;
    public javax.swing.JMenuItem jMenuItem4_gestionar_producto;
    public javax.swing.JMenuItem jMenuItem5_actualizar_stock;
    public javax.swing.JMenuItem jMenuItem6_nueva_categoria;
    public javax.swing.JMenuItem jMenuItem7_gestionar_categoria;
    private javax.swing.JMenuItem jMenuItem8;
    public javax.swing.JMenuItem jMenuItem9_nueva_venta;
    public javax.swing.JLabel jtxNombreEmpleado;
    public javax.swing.JMenuItem mncerrarPanel;
    public javax.swing.JMenuItem volvermenu;
    // End of variables declaration//GEN-END:variables
}
